-- Tạo database
CREATE DATABASE quanlyspa;
USE quanlyspa;

-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MAKH INT PRIMARY KEY AUTO_INCREMENT,
    TEN VARCHAR(100) NOT NULL,
    DCHI VARCHAR(255),
    DTHOAI VARCHAR(15),
    EMAIL VARCHAR(100) UNIQUE,
    MATKHAU VARCHAR(255)
);

-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY AUTO_INCREMENT,
    TEN VARCHAR(100) NOT NULL,
    DCHI VARCHAR(255),
    DTHOAI VARCHAR(15),
    CHUYENMON VARCHAR(100),
    DIEMDANHGIA FLOAT DEFAULT 0,
    HINHANH VARCHAR(255)
);

-- Bảng LOAIDICHVU
CREATE TABLE LOAIDICHVU (
    MALOAI INT PRIMARY KEY AUTO_INCREMENT,
    TENLOAI VARCHAR(100) NOT NULL,
    MOTA TEXT
);

-- Bảng DICHVU
CREATE TABLE DICHVU (
    MADV INT PRIMARY KEY AUTO_INCREMENT,
    TEN VARCHAR(100) NOT NULL,
    MOTA TEXT,
    THOIGIANTHUCHIEN INT NOT NULL, -- tính bằng phút
    GIATIEN DECIMAL(10,2),
    MALOAI INT,
    FOREIGN KEY (MALOAI) REFERENCES LOAIDICHVU(MALOAI)
);

-- Bảng TRANGTHAILICHDAT
CREATE TABLE TRANGTHAILICHDAT (
    MATRANGTHAI INT PRIMARY KEY AUTO_INCREMENT,
    TENTRANGTHAI VARCHAR(50) UNIQUE NOT NULL,
    MOTA TEXT
);

-- Bảng LICHDAT
CREATE TABLE LICHDAT (
    MALICH INT PRIMARY KEY AUTO_INCREMENT,
    MAKH INT,
    MANV INT,
    MADV INT,
    THOIGIANBATDAU DATETIME,
    THOIGIANKETTHUC DATETIME,
    MATRANGTHAI INT,
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MADV) REFERENCES DICHVU(MADV),
    FOREIGN KEY (MATRANGTHAI) REFERENCES TRANGTHAILICHDAT(MATRANGTHAI)
);

-- Bảng DANHGIA
CREATE TABLE DANHGIA (
    MADG INT PRIMARY KEY AUTO_INCREMENT,
    MAKH INT,
    MANV INT,
    SOSAO INT CHECK(SOSAO BETWEEN 1 AND 5),
    BINHLUAN TEXT,
    NGAYDANHGIA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bảng LICHLAMVIEC
CREATE TABLE LICHLAMVIEC (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MANV INT,
    NGAYLAM DATE,
    THOIGIANBATDAU TIME,
    THOIGIANKETTHUC TIME,
    TRANGTHAI ENUM('Đang làm việc', 'Nghỉ', 'Vắng mặt') DEFAULT 'Đang làm việc',
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bảng THANHTOAN
CREATE TABLE THANHTOAN (
    MATHANHTOAN INT PRIMARY KEY AUTO_INCREMENT,
    MALICH INT,
    MAKH INT,
    SOTIEN DECIMAL(10,2),
    NGAYTHANHTOAN DATETIME DEFAULT CURRENT_TIMESTAMP,
    HINHTHUCTHANHTOAN ENUM('Tiền mặt', 'Chuyển khoản', 'Online'),
    FOREIGN KEY (MALICH) REFERENCES LICHDAT(MALICH),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- Bảng QUANTRIVIEN
CREATE TABLE QUANTRIVIEN (
    MAQT INT PRIMARY KEY AUTO_INCREMENT,
    TEN VARCHAR(100),
    DTHOAI VARCHAR(15),
    EMAIL VARCHAR(100) UNIQUE,
    MATKHAU VARCHAR(255)
);

INSERT INTO LOAIDICHVU (TENLOAI, MOTA) VALUES 
('Massage', 'Các gói massage thư giãn toàn thân'),
('Chăm sóc da', 'Liệu trình dưỡng da cao cấp');

INSERT INTO DICHVU (TEN, MOTA, THOIGIANTHUCHIEN, GIATIEN, MALOAI) VALUES
('Massage Thái cổ truyền', 'Massage giúp giảm đau nhức và thư giãn', 60, 300000, 1),
('Massage đá nóng', 'Thư giãn với nhiệt từ đá nóng', 45, 250000, 1),
('Chăm sóc da mặt chuyên sâu', 'Làm sạch sâu và dưỡng da', 60, 400000, 2);
